### ISSUE TITLE
cleanup_tmp入りますか？

### ISSUE THREAD

**Issue by drakontia** [mikoto20000/redmine_git_branch_hook#1]
こんにちわ。drakontiaです。

たまたま、これだけALMiniumとは別環境にいれたのですが、
途中エラーが出まして。

init.rbでrequire 'cleanup_tmp'しているのですが、
これはredmine_attach_screenshotのlibにあるものだと思います。
まだRuby勉強中で間違っているかもしれませんが、
このプラグインでは使われていないような気がします。

それとも、このプラグインはALMinium前提でしょうか。
すいません。どうしても気になりまして。

**Comment by mikoto20000** [comment]
ご報告ありがとうございます。

redmine_attach_screenshotを参考にしながら作成したので、
ゴミが残っていました。

修正しました。よろしくお願いします。

**Comment by drakontia** [comment]
ありがとうございます。
おかげですっきりしました。
